### ISSUE TITLE
Will you make a version for shipping games?

### ISSUE THREAD

**Issue by TheRealFame** [MrEliptik/game_launcher#43]
Header! I'm curious, I always wanted to develop my own launcher! (Not to be forced, But to play games that won't be released in steam.)

**Comment by MrEliptik** [comment]
I don't plan on doing it because it's much more work than what I did for this launcher. It would need to support the other launcher, automatically import games, etc.. There are launchers out there like Playnite that should do the trick. You can definitely use this as a starting point if you want though!
